### ISSUE TITLE
Frontend Latest Study: Notice

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#518]
Notice: Undefined property: stdClass::$bookname2 in ...\components\com_biblestudy\lib\listing.php on line 1920

Maybe it has to do with the study; it is a study with book 1 and book 2.

**Comment by tomfuller2** [comment]
This is fixed

**Comment by st-anton** [comment]
Not fixed. It appears as soon, as a book 2 is defined for the study.
Happens also on Frontend Single Study.

**Comment by tomfuller2** [comment]
I'm not getting any errors showing book2 with latest study. Here is one on my test site:
http://joomlaoregon.com/jbs/index.php/latest-study/sermon/940/1

**Comment by st-anton** [comment]
I reviewed my set of files and found a file that was not taken over by mistake (models/sermon.php). With the actual one, it is fixed. Sorry for this!
-> Closed
