### ISSUE TITLE
Frontend new / edit study: No entry for access level

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Joomla-Bible-Study#571]
Access level can be set in the backend, but not in the frontend

**Comment by bcordis** [comment]
I'm not sure there is a way in the fontend but I'll look to see if it's
able.

On Wednesday, May 27, 2015, st-anton <notifications@github.com> wrote:

> Access level can be set in the backend, but not in the frontend
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/issues/571>.
>


-- 
Sent from Gmail Mobile

**Comment by st-anton** [comment]
Cannot find the field.

**Comment by bcordis** [comment]
@st-anton @tomfuller2 Right now its in different spots compared to the backend Should we make it the same?

**Comment by bcordis** [comment]
Fixed.

**Comment by st-anton** [comment]
The field is still missing. I tried the following code and it worked as expected:
site\components\com_biblestudy\views\messageform\tmpl\edit.php line 373

						<div class="control-group">
							<div class="control-label">
								<?php echo $this->form->getLabel('access'); ?>
							</div>
							<div class="controls">
								<?php echo $this->form->getInput('access'); ?>
							</div>
						</div>

**Comment by bcordis** [comment]
You are right the rules are there but the access is missing. Will add ASAP.
